/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainWindow;

import Entities.Account;
import Panels.LoginPanel;
import Panels.LoginPanel.LoginPageListener;
import Panels.MainPanel;
import Panels.MainPanel.MainPageListener;
import Panels.SignupPanel;
import Panels.SignupPanel.SignupPageListener;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author guess
 */
public class MainWindow extends javax.swing.JFrame implements LoginPageListener, SignupPageListener, MainPageListener{

    /**
     * Creates new form MainWindow
     */
    
    LoginPanel loginpanel;
    SignupPanel signupPanel;
    MainPanel mainPanel;
    
     
    public MainWindow() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        displayLoginPage();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        
    }
    
    private void displayMainPage(Account account){
        mainPanel = new MainPanel(this, account);
        mainPanel.addPageListener(this);
        panel_body.setViewportView(mainPanel);
    }
    
    private void displayLoginPage(){
        loginpanel = new LoginPanel(this);
        loginpanel.addPageListener(this);
        panel_body.setViewportView(loginpanel);

    }
    
    private void displaySignupPage(){
        signupPanel = new SignupPanel(this);
        signupPanel.addPageListener(this);
        panel_body.setViewportView(signupPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_body = new javax.swing.JScrollPane();
        menubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_reports = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Title Here");

        panel_body.setBorder(null);
        panel_body.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        getContentPane().add(panel_body, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuItem_reports.setText("Reporting");
        menuItem_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_reportsActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_reports);

        menubar.add(jMenu1);

        jMenu2.setText("Edit");
        menubar.add(jMenu2);

        setJMenuBar(menubar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_reportsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuItem_reportsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem menuItem_reports;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JScrollPane panel_body;
    // End of variables declaration//GEN-END:variables

 
    @Override
    public void onSuccessLogin(Account account) {
        displayMainPage(account);
    }

    @Override
    public void onSignupButtonClicked() {
        displaySignupPage();
    }

    @Override
    public void onSuccesfulSignup() {
        displayLoginPage();
    }

    @Override
    public void onCancelSignup() {
        displayLoginPage();
    }

    @Override
    public void onLogoutButtonClicked() {
        displayLoginPage();
    }
}
